### ISSUE TITLE
v0.7.1 breaks mappings

### ISSUE THREAD

**Issue by ofek** [sdispater/tomlkit#124]
Similar to #113 cc @sdispater @frostming

```pycon
>>> from copy import deepcopy
>>> import tomlkit
>>>
>>> doc = tomlkit.parse("""
... [tool.project.section]
... option = 'foo'
... """)
>>>
>>> doc
{'tool': {'project': {'section': {'option': 'foo'}}}}
>>> doc['tool']
{'project': {'section': {'option': 'foo'}}}
>>> doc['tool']['project']
{'section': {'option': 'foo'}}
>>> doc['tool']['project']['section']
{'option': 'foo'}
>>> 'option' in doc['tool']['project']['section']
True
>>> list(doc['tool']['project']['section'].items())
[('option', 'foo')]
>>> options = deepcopy(doc['tool']['project']['section'])
>>> 'option' in options
True
>>> options['option']
'foo'
>>> list(options.items())
[]
>>> possible_option = options.pop('option', None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\lib\_collections_abc.py", line 801, in pop
    del self[key]
  File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\lib\site-packages\tomlkit\items.py", line 1034, in __delitem__
    self.remove(key)
  File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\lib\site-packages\tomlkit\items.py", line 960, in remove
    self._value.remove(key)
  File "C:\Users\ofek\AppData\Local\Programs\Python\Python38\lib\site-packages\tomlkit\container.py", line 267, in remove
    dict.__delitem__(self, key.key)
KeyError: 'option'
```

**Comment by frostming** [comment]
Table doesn't implement deepcopy protocol, the workaround is to `deepcopy(dict(table))`

**Comment by ofek** [comment]
@frostming Still not working:

```pycon
>>> from copy import deepcopy
>>> import tomlkit
>>>
>>> doc = tomlkit.parse("""
... [tool.project.section]
... option = 'foo'
... """)
>>>
>>> root = deepcopy(dict(doc))
>>> options = deepcopy(dict(root['tool']['project']['section']))
>>>
>>> list(options.items())
[]
```
