### ISSUE TITLE
`Table.values()` crash: `IndexError: list index out of range`

### ISSUE THREAD

**Issue by tusharsadhwani** [sdispater/tomlkit#184]
I faced this crash while making a PR for another open source project:

```
Traceback (most recent call last):
  File "/home/tushar/code/pyproject-fmt/mytest.py", line 14, in <module>
    for item in table.values():
  File "/usr/lib/python3.10/_collections_abc.py", line 922, in __iter__
    yield self._mapping[key]
  File "/home/tushar/code/pyproject-fmt/venv/lib/python3.10/site-packages/tomlkit/items.py", line 1267, in __getitem__
    return cast(Item, self._value[key])
  File "/home/tushar/code/pyproject-fmt/venv/lib/python3.10/site-packages/tomlkit/container.py", line 614, in __getitem__
    item = self._body[idx][1]
IndexError: list index out of range
```

Here's the minimal reproduction for this:

```python
import tomlkit

document = tomlkit.parse(
    """
    [foo]
    a = 10
    """
)

table = document["foo"]
table.value.body.clear()
for item in table.values():
    ...
```
The reason seems to be that `table.value._map` is not updated when you directly update the internal `body` list.

---

I don't know if modifying the `table.value.body` list is supported or if it is "undefined behaviour". If this isn't the intended method, what's the right way to do this sort of table manipulation?

**Comment by frostming** [comment]
You shouldn't operate on the internal data attribute. To clear a table simply calls `table.clear()`.

I consider this isn't a bug.
