### ISSUE TITLE
float addition with tomlkit.items.Integer raises a NotImplementedType Exception

### ISSUE THREAD

**Issue by Poofjunior** [sdispater/tomlkit#214]
Title says it all. Adding a tomlkit.items.Integer with a float will raise a NotImplementedType exception.

Here's the breaking code:
````
content = '[table]\nmy_int = 2048'
doc  = parse(content)

doc['table']['my_int'] + 5.0
````

## System Info
Python version: 3.8.13
Tomlkit version: 0.11.1
OS: Windows 10

## Other stuff
Some quick googling looks like the same issue shows up in another project [here](https://github.com/optuna/optuna/issues/3652).

**Comment by SamirPS** [comment]
Do you have the logs of the error ?

**Comment by Poofjunior** [comment]
I do! Here's the stack trace:
````
Traceback (most recent call last):
  File "C:\Users\joshua.vasquez\.conda\envs\spim\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\joshua.vasquez\.conda\envs\spim\lib\site-packages\tomlkit\items.py", line 635, in __add__
    return self._new(result)
  File "C:\Users\joshua.vasquez\.conda\envs\spim\lib\site-packages\tomlkit\items.py", line 665, in _new
    return Integer(result, self._trivia, raw)
  File "C:\Users\joshua.vasquez\.conda\envs\spim\lib\site-packages\tomlkit\items.py", line 606, in __new__
    return super().__new__(cls, value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NotImplementedType'
````

**Comment by SamirPS** [comment]
I didn't check the code but if you convert the doc['table']['my_int'] to int it's works ?

**Comment by SamirPS** [comment]
i thinks it's line 640 on items.py :         result = super().__add__(other)

**Comment by SamirPS** [comment]
if you do : doc['table']['my_int'] + 5 it's work
