### ISSUE TITLE
"IndexError: list index out of range" when using dotkeys and non-dotkeys

### ISSUE THREAD

**Issue by fflorent** [sdispater/tomlkit#273]
**Version of tomlkit**: 0.11.6

I get an exception when running this script (this seems to be the minimal scenario):

```python
import tomlkit

t = tomlkit.table()
t.add('foo', 2)
t.add(tomlkit.key(["bar", "baz"]), 1)
t.add(tomlkit.key(["bar", "qux"]), 1)
```

I expect to be able to output something like this (using `t.as_string()`):
```toml
foo = 2
bar.baz = 1
bar.qux = 1
```

Instead, I get this exception:
```
Traceback (most recent call last):
  File "/tmp/script.py", line 6, in <module>
    t.add(tomlkit.key(["bar", "qux"]), 1)
  File "/usr/lib/python3/dist-packages/tomlkit/items.py", line 1478, in add
    return self.append(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/tomlkit/items.py", line 1584, in append
    self._value.append(key, _item)
  File "/usr/lib/python3/dist-packages/tomlkit/container.py", line 188, in append
    self._handle_dotted_key(key, item)
  File "/usr/lib/python3/dist-packages/tomlkit/container.py", line 150, in _handle_dotted_key
    self.append(name, value)
  File "/usr/lib/python3/dist-packages/tomlkit/container.py", line 243, in append
    self._table_keys[-1] != current_body_element[0]
    ~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by frostming** [comment]
This should be fixed by #284
