### ISSUE TITLE
Parser regression in 0.5.2 in pypy3(6.0.0)

### ISSUE THREAD

**Issue by extraymond** [sdispater/tomlkit#33]
Hi! I've encountered parser regression in 0.5.2 in pypy3(6.0.0), when trying to use poetry, it says that it have problem parsing the toml file.

After investigation, I've found that in pypy3(6.0.0) this behavior exists while not affecting normal python 3.5 environments.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/toml/site-packages/tomlkit/api.py", line 51, in parse
    return Parser(string).parse()
  File "/home/user/.pyenv/versions/toml/site-packages/tomlkit/parser.py", line 153, in parse
    key, value = self._parse_table()
  File "/home/user/.pyenv/versions/toml/site-packages/tomlkit/parser.py", line 975, in _parse_table
    is_aot_next, name_next = self._peek_table()
TypeError: 'NoneType' object is not iterable
```

**Comment by sdispater** [comment]
It is fixed in the latest `0.5.3` release.
