### ISSUE TITLE
KeyAlreadyPresent raised when it should be valid

### ISSUE THREAD

**Issue by batisteo** [sdispater/tomlkit#4]
```python
# Python 3.6.5
toml_file = """
[[patterns]]
[patterns.start.0]
name = "name 0"
[patterns.start.1]
name = "name 1"
"""

import toml, tomlkit

toml.loads(toml_file)
# {'patterns': [{'start': {'0': {'name': 'name 0'}, '1': {'name': 'name 1'}}}]}


tomlkit.loads(toml_file)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
    tomlkit.loads(toml_file)
  File "/~/.venv/lib64/python3.6/site-packages/tomlkit/api.py", line 38, in loads
    return parse(string)
  File "/~/.venv/lib64/python3.6/site-packages/tomlkit/api.py", line 52, in parse
    return Parser(string).parse()
  File "/~/.venv/lib64/python3.6/site-packages/tomlkit/parser.py", line 170, in parse
    key, value = self._parse_table()
  File "/~/.venv/lib64/python3.6/site-packages/tomlkit/parser.py", line 935, in _parse_table
    values.append(key_next, table_next)
  File "/~/.venv/lib64/python3.6/site-packages/tomlkit/container.py", line 103, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "start" already exists.
```

**Comment by sdispater** [comment]
Which version of TOML Kit are you using?

On the latest `0.3.0` version, it works fine on my end:

```python
>>> import tomlkit
>>> toml_file = """
[[patterns]]
[patterns.start.0]
name = "name 0"
[patterns.start.1]
name = "name 1"
"""
>>> tomlkit.loads(toml_file)
{'patterns': [{'start': {'0': {'name': 'name 0'}, '1': {'name': 'name 1'}}}]}
```

**Comment by batisteo** [comment]
__Mon mauvais__
