### ISSUE TITLE
Apostrophe (single-quote) in key string causes problems

### ISSUE THREAD

**Issue by jgriffitts** [sdispater/tomlkit#70]
This code sequence demonstrates the problem:
```
import tomlkit

dat = {"BJ's Restaurant": {'account':'dining'}}

toml = tomlkit.dumps(dat)
print(toml)

dat2 = tomlkit.loads(toml)
```
This gives me this output (Python 3.7.6):
```
["BJ's Restaurant"]
account = "dining"

Traceback (most recent call last):
  File "j:\tmp.py", line 17, in <module>
    dat2 = tomlkit.loads(toml)
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\api.py", line 34, in loads
    return parse(string)
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\api.py", line 51, in parse
    return Parser(string).parse()
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\parser.py", line 153, in parse
    key, value = self._parse_table()
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\parser.py", line 927, in _parse_table
    name_parts = tuple(self._split_table_name(name))
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\parser.py", line 227, in _split_table_name
    raise self.parse_error()
tomlkit.exceptions.ParseError: TOML parse error at line 1 col 18
```
The TOML generated by dumps(dat) shows in the first two lines, and seems correct. However loads() blows up as shown, calling out column 18 which would be the end of the key string. 
For the TOML source below, loads() calls out column 0, which is possibly a different bug:
```
[xyz]
[xyz."BJ's Restaurant"]
account = "dining"
---------------
  File "c:\ProgramData\Miniconda3\envs\hledger\lib\site-packages\tomlkit\parser.py", line 227, in _split_table_name
    raise self.parse_error()
tomlkit.exceptions.ParseError: TOML parse error at line 2 col 0
```

I have experimented with work-arounds such as enclosing the string in triple-quotes or escaping the apostrophe with a backslash. So far, I haven't found anything reliable.

**Comment by jgriffitts** [comment]
Putting in this change seems to fix it for my use case. I don't really understand the code I'm patching so I don't know if this is safe, but  `pytest` passes. I think this fix is probably incomplete. Should there be a similar test for embedded double-quotes?
```
index ecb2a75..1498857 100644
--- a/tomlkit/parser.py
+++ b/tomlkit/parser.py
@@ -224,6 +224,9 @@ class Parser:
                         continue

                     if c != t.value:
+                        if c == "'" and t.value == '"':
+                            current += c
+                            continue
                         raise self.parse_error()

                     in_name = False
```
