### ISSUE TITLE
Builtin type subclasses don't play nice with parts of the standard library.

### ISSUE THREAD

**Issue by acetylen** [sdispater/tomlkit#73]
```python
Python 3.7.3 (default, Oct  7 2019, 12:56:13)
[GCC 8.3.0] on linux

>>> import tomlkit, socket

>>> cfg = tomlkit.parse( "ip = '127.0.0.1'\nport = 1883")
>>> address = (cfg['ip'], cfg['port'])

>>> socket.create_connection(address)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected

>>> address = ('127.0.0.1', 1883)
>>> s = socket.create_connection(address)
>>> s.close()  # connection works (requires someone listening at 1883, of course)
```

I don't understand why this doesn't work. After all, they seem to inherit the right types.
```python
>>> type(cfg['ip']).mro()
[<class 'tomlkit.items.String'>, <class 'str'>, <class 'tomlkit.items.Item'>, <class 'object'>]
>>> type(cfg['port']).mro()
[<class 'tomlkit.items.Integer'>, <class 'int'>, <class 'tomlkit.items.Item'>, <class 'object'>]
```

**Comment by nomme** [comment]
I just encountered this issue as well. Wasn't aware tomlkit wraps basic types like this... Took me a few hours to figure out as the library which handles the sockets does some, not so helpful, catch all try-excepts.

I found some variations which changes the behavior.
```python
# This actually works for me
cfg = tomlkit.parse("ip = '127.0.0.1'\nport = 1883")
# So does this
cfg = tomlkit.parse("ip = 'localhost'\nport = '1883'")

# But this does not work
cfg = tomlkit.parse("ip = 'localhost'\nport = 1883")
```
So I only have issues when using an URL in combination with an int as port, which is the normal case.

**Comment by frostming** [comment]
The wrapped types are the cost paid to preserve the styles. However, libraries treat them differently, you should always use factory methods to ensure they are primitive:

```python
hostname = str(config['ip'])
# or
hostname = config['ip'].value
```
